### ISSUE TITLE
Add link to this on Pi-hole.net

### ISSUE THREAD

**Issue by jacobsalmela** [dstinebaugh/pihole-led#1]
Just wondering if we could add this to our [FAQs](https://pi-hole.net/faq/i-want-to-hook-up-an-led-to-blink-whenever-something-happens-ad-is-blocked-dns-query-is-served-whatever-how-can-i-hook-into-pi-hole/) and/or feature it on our main github page?

**Comment by dstinebaugh** [comment]
Of course you can, I'd be very pleased! Use it where and how you wish!

**Comment by jacobsalmela** [comment]
Thanks!
